--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/run/media/kevin/DATATB/datos/Imágenes/Surtr/1189209.png"

-- Special
background="#000000"
foreground="#e1ccd1"
cursor="#e1ccd1"

-- Colors
color0="#000000"
color1="#A5292E"
color2="#B1424E"
color3="#A55860"
color4="#D16061"
color5="#986E8C"
color6="#DEA6A5"
color7="#e1ccd1"
color8="#9d8e92"
color9="#A5292E"
color10="#B1424E"
color11="#A55860"
color12="#D16061"
color13="#986E8C"
color14="#DEA6A5"
color15="#e1ccd1"
