# Shell variables
# Generated by 'wal'
wallpaper='/media/DATOS/Imágenes/Wallpapers/106111744_p0.png'

# Special
background='#000000'
foreground='#f3dbd4'
cursor='#f3dbd4'

# Colors
color0='#000000'
color1='#94152B'
color2='#D53C4B'
color3='#A45F63'
color4='#B57389'
color5='#AD9DA2'
color6='#E1A59E'
color7='#f3dbd4'
color8='#aa9994'
color9='#94152B'
color10='#D53C4B'
color11='#A45F63'
color12='#B57389'
color13='#AD9DA2'
color14='#E1A59E'
color15='#f3dbd4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
