--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/media/DATOS/Imágenes/Wallpapers/Abstract-Green-HD-Wallpaper.jpg"

-- Special
background="#000000"
foreground="#e4eadf"
cursor="#e4eadf"

-- Colors
color0="#000000"
color1="#57AB4F"
color2="#75C55C"
color3="#88BD6B"
color4="#8DCB6A"
color5="#76AD88"
color6="#B5D69A"
color7="#e4eadf"
color8="#9fa39c"
color9="#57AB4F"
color10="#75C55C"
color11="#88BD6B"
color12="#8DCB6A"
color13="#76AD88"
color14="#B5D69A"
color15="#e4eadf"
