# Shell variables
# Generated by 'wal'
wallpaper='/media/DATOS/Imágenes/Wallpapers/surtr_arknights__by_kepinn_dehdzhl.png'

# Special
background='#000000'
foreground='#e6e0e1'
cursor='#e6e0e1'

# Colors
color0='#000000'
color1='#9A1420'
color2='#E61326'
color3='#EF3648'
color4='#BD4753'
color5='#A39D9E'
color6='#D0B7BB'
color7='#e6e0e1'
color8='#a19c9d'
color9='#9A1420'
color10='#E61326'
color11='#EF3648'
color12='#BD4753'
color13='#A39D9E'
color14='#D0B7BB'
color15='#e6e0e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
