# Shell variables
# Generated by 'wal'
wallpaper='/media/DATOS/Imágenes/Wallpapers/Surtr-28_upscayl_4x_realesrgan-x4plus-anime.jpg'

# Special
background='#000000'
foreground='#cdd3db'
cursor='#cdd3db'

# Colors
color0='#000000'
color1='#9A232E'
color2='#BC494F'
color3='#888187'
color4='#9F9B9F'
color5='#D4A99B'
color6='#F1CBB8'
color7='#cdd3db'
color8='#8f9399'
color9='#9A232E'
color10='#BC494F'
color11='#888187'
color12='#9F9B9F'
color13='#D4A99B'
color14='#F1CBB8'
color15='#cdd3db'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
