--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kevin/Imágenes/Surtr/Arknights-Surtr-Icon.png"

-- Special
background="#000000"
foreground="#e9d6d3"
cursor="#e9d6d3"

-- Colors
color0="#000000"
color1="#AE3134"
color2="#BE4A4C"
color3="#AF5858"
color4="#D3585D"
color5="#CE7C87"
color6="#DFA99E"
color7="#e9d6d3"
color8="#a39593"
color9="#AE3134"
color10="#BE4A4C"
color11="#AF5858"
color12="#D3585D"
color13="#CE7C87"
color14="#DFA99E"
color15="#e9d6d3"
