#!/bin/bash

function getbg {
		cat ~/.config/pcmanfm-qt/lxqt/settings.conf | grep Wallpaper=/ | cut -d"=" -f2
}

if [ ${auto_lock_set_wallpaper}=1 ]; then
	lockwallpaper=$(getbg)
	echo ${lockwallpaper}
	betterlockscreen -u ${lockwallpaper}
	sed -i 's|lockwallpaper=.*|lockwallpaper='"${lockwallpaper}"'|g' ~/.config/lxqt/session.conf
else
	echo "Automatic setting of lockscreen wallpaper is OFF"
fi
