#!/bin/bash
function checkwm {
    wmctrl -m
    exitstatus=$?
}

checkwm

 if [ "$exitstatus" = 0 ]; then
    echo "Opening panel"
    while [ "$exitstatus" = 1 ]; do checkwm; sleep 1; done
    tint2 &
 else
    echo "Window manager not running"
    while [ "$exitstatus" = 1 ]; do checkwm; sleep 1; done
    tint2 &
 fi
