#!/bin/bash
function checkwm {
    wmctrl -m
    exitstatus=$?
}

checkwm

 if [ "$exitstatus" = 0 ]; then
    echo "Opening apps"
    while [ "$exitstatus" = 1 ]; do checkwm; sleep 2; done
    #gpu-video-wallpaper --start "$(cat ~/.config/video-wallpaper/settings.conf | grep lastfile | cut -d"=" -f2 | cut -d'"' -f2)" &
    $BAR_APPLICATION &
    sleep 2
    ~/scripts/patray &
    # nitrogen --restore &
    wpa-cute -qt &
 else
    echo "Window manager not running"
    while [ "$exitstatus" = 1 ]; do checkwm; sleep 2; done
    #gpu-video-wallpaper --start "$(cat ~/.config/video-wallpaper/settings.conf | grep lastfile | cut -d"=" -f2 | cut -d'"' -f2)" &
    $BAR_APPLICATION &
    sleep 2
    ~/scripts/patray &
    # nitrogen --restore &
    wpa-cute -qt &
 fi
